### ISSUE TITLE
Hospitality: Bugged Guest beds, cant remove

### ISSUE THREAD

**Issue by GarretSidzaka** [OrionFive/Hospitality#536]
**Describe the bug**
Two beds on my map that were marked for guests now cant be removed in debug mode, nor can the colonoists remove them.  they just go do other things after the task bar timer finishes.

**To Reproduce**
Click on "glitched" guest bed
get stack trace
colonists nor debug can remove

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
GetInspectString exception on BedGuest1402356:
System.NullReferenceException: Object reference not set to an instance of an object
  at Hospitality.Building_GuestBed.GetInspectString () [0x00085] in <f7f6b1b841ba4733b81d7ee58f78f413>:0 
  at RimWorld.InspectPaneFiller.DrawInspectStringFor (Verse.ISelectable sel, UnityEngine.Rect rect) [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
RimWorld.InspectPaneFiller:DrawInspectStringFor(ISelectable, Rect)
RimWorld.InspectPaneFiller:RimWorld.InspectPaneFiller.DoPaneContentsFor_Patch1(ISelectable, Rect)
RimWorld.MainTabWindow_Inspect:DoPaneContents(Rect)
RimWorld.InspectPaneUtility:RimWorld.InspectPaneUtility.InspectPaneOnGUI_Patch1(Rect, IInspectPane)
RimWorld.MainTabWindow_Inspect:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

```

**Comment by OrionFive** [comment]
Thanks, this was useful. I've pushed a new version. Hopefully, it's fixed now.

**Comment by GarretSidzaka** [comment]
i will test in a couple hours :)

**Comment by GarretSidzaka** [comment]
new behavior, i can see the 40 silver piece costs

bug still there i cannot remove the bed

here is my colonist Gregory's attempt:

```
JobDriver threw exception in initAction for pawn Greggory driver=JobDriver_Deconstruct (toilIndex=2) driver.job=(Deconstruct (Job_11572809) A=Thing_BedGuest1402356)
System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.Building_Bed.RemoveAllOwners () [0x0001c] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Building_Bed.DeSpawn (Verse.DestroyMode mode) [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Hospitality.Building_GuestBed.DeSpawn (Verse.DestroyMode mode) [0x0002f] in <f729025bc3574ba28cb789c183a0ce0d>:0 
  at Verse.Thing.Destroy (Verse.DestroyMode mode) [0x00053] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.ThingWithComps.Destroy (Verse.DestroyMode mode) [0x00007] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at (wrapper dynamic-method) Verse.Building.Verse.Building.Destroy_Patch2(Verse.Building,Verse.DestroyMode)
  at RimWorld.JobDriver_Deconstruct.FinishedRemoving () [0x00006] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.JobDriver_RemoveBuilding.<MakeNewToils>b__12_4 () [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001df] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
RimWorld.<>c__DisplayClass12_0:<MakeNewToils>b__1()
Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch1(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch1(Pawn)
Verse.TickList:Tick()
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch3(TickManager)
Verse.TickManager:Verse.TickManager.TickManagerUpdate_Patch4(TickManager)
Verse.Game:Verse.Game.UpdatePlay_Patch2(Game)
Verse.Root_Play:Update()
```

**Comment by GarretSidzaka** [comment]
```
Exception ticking BedGuest1402356 (at (216, 0, 107)). Suppressing further errors. Exception: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.CompAssignableToPawn_Bed.TryUnassignPawn (Verse.Pawn pawn, System.Boolean sort) [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Hospitality.Building_GuestBed.TickLong () [0x00038] in <f729025bc3574ba28cb789c183a0ce0d>:0 
  at Verse.TickList.Tick () [0x0017a] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Verse.Log.Error_Patch2(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
Verse.TickList:Tick()
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch3(TickManager)
Verse.TickManager:Verse.TickManager.TickManagerUpdate_Patch4(TickManager)
Verse.Game:Verse.Game.UpdatePlay_Patch2(Game)
Verse.Root_Play:Update()
```

**Comment by OrionFive** [comment]
I think I found the problem. I'm not making a public update yet, because I have to fix another bug. But you can download the latest version [here](https://github.com/OrionFive/Hospitality/archive/refs/heads/develop.zip) and test it.

**Comment by GarretSidzaka** [comment]
that fixed both of these glitched beds!   nice work, thank you
