### ISSUE TITLE
Proposal: tags and branches

### ISSUE THREAD

**Issue by Blu3wolf** [OrionFive/Hospitality#8]
I would suggest merging your current A15 version of Hospitality into master, and adding a tag to that commit for A15. You could also make a Release at that point if you wanted to as well. Then, when your release branch is ready for a final release on A16, you can merge it into master, tag it for A16, and make a Release there.

**Comment by OrionFive** [comment]
Hm. I've already merged A16 into master, so I think merging A15 now will probably do more damage than good. I could still make a release for A15. But since it's available on Steam and the forums, I don't think this is really necessary.

**Comment by Blu3wolf** [comment]
I missed that merge! All good then!

**Comment by Blu3wolf** [comment]
Im seeing master as still not including A16 at this point. Im looking at master being up to 22b78 ?

**Comment by OrionFive** [comment]
My bad. Apparently I still had to merge your master with mine.

**Comment by Blu3wolf** [comment]
Well, we just did that - #10 merged my master branch with yours. My master branch didnt have the actual project in it, though, just the license, contribution and readme files in it. 

You can merge the A16 and master branches, but this would bring master up to wherever A16 is. Id suggest leaving master at whatever your last stable release for any version of rimworld is (I assume that is A15). This would be keeping in line with the Git Flow concept for workflow, which Im personally a fan of and would recommend.

**Comment by OrionFive** [comment]
I think I got it now.
