### ISSUE TITLE
Gastronomy: With Medieval Overhaul, pawn can't find food

### ISSUE THREAD

**Issue by ZXUW** [OrionFive/Hospitality#839]
**Describe the bug**
Medieval Overhaul (Feb 23 update) and Gastronomy, pawn can't find food

**To Reproduce**
1. Gastronomy run with Medieval Overhaul (and it's frame)
2. set up dining table with chair
3. when pawn hungry, and try to get food, it report an error

**Console log**
https://gist.github.com/HugsLibRecordKeeper/c13cd77d41e383ce356da214b3cbbe61

**Error stacktrace**
The error has extra information that is not included in the log. Please select it in the console and copy the whole error message.
```
Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.NotImplementedException: The method or operation is not implemented.
[Ref 26A4B5F0]
 at Gastronomy.Dining.DiningSpot.get_DispensableDef () [0x00000] in <b054b553719642b589b9bb1f9b2831f2>:0 
 at RimWorld.FoodUtility.GetFinalIngestibleDef (Verse.Thing foodSource, System.Boolean harvest) [0x0000a] in <69945a8ed6c540cf90b578de735e0605>:0 
 at RimWorld.FoodUtility.SpawnedFoodSearchInnerScan (Verse.Pawn eater, Verse.IntVec3 root, System.Collections.Generic.List`1[T] searchSet, Verse.AI.PathEndMode peMode, Verse.TraverseParms traverseParams, System.Single maxDistance, System.Predicate`1[T] validator) [0x0005b] in <69945a8ed6c540cf90b578de735e0605>:0 
 at RimWorld.FoodUtility.BestFoodSourceOnMap (Verse.Pawn getter, Verse.Pawn eater, System.Boolean desperate, Verse.ThingDef& foodDef, RimWorld.FoodPreferability maxPref, System.Boolean allowPlant, System.Boolean allowDrug, System.Boolean allowCorpse, System.Boolean allowDispenserFull, System.Boolean allowDispenserEmpty, System.Boolean allowForbidden, System.Boolean allowSociallyImproper, System.Boolean allowHarvest, System.Boolean forceScanWholeMap, System.Boolean ignoreReservations, System.Boolean calculateWantedStackCount, RimWorld.FoodPreferability minPrefOverride, System.Nullable`1[T] minNutrition, System.Boolean allowVenerated) [0x00299] in <69945a8ed6c540cf90b578de735e0605>:0 
     - TRANSPILER medievalOverhaul: IEnumerable`1 MedievalOverhaul.FoodUtility_BestFoodSourceOnMap_HelperFind:Transpiler(IEnumerable`1 instructions)
     - POSTFIX Orion.Hospitality: Void Hospitality.Patches.FoodUtility_Patch+BestFoodSourceOnMapPatch:Postfix(Pawn getter, Pawn eater, Boolean desperate, ThingDef foodDef, Thing& __result)
 at RimWorld.FoodUtility.TryFindBestFoodSourceFor (Verse.Pawn getter, Verse.Pawn eater, System.Boolean desperate, Verse.Thing& foodSource, Verse.ThingDef& foodDef, System.Boolean canRefillDispenser, System.Boolean canUseInventory, System.Boolean canUsePackAnimalInventory, System.Boolean allowForbidden, System.Boolean allowCorpse, System.Boolean allowSociallyImproper, System.Boolean allowHarvest, System.Boolean forceScanWholeMap, System.Boolean ignoreReservations, System.Boolean calculateWantedStackCount, System.Boolean allowVenerated, RimWorld.FoodPreferability minPrefOverride) [0x00261] in <69945a8ed6c540cf90b578de735e0605>:0 
     - PREFIX Orion.Gastronomy: Boolean Gastronomy.Dining._TryBestFoodSourceFor_Patch+TryFindBestFoodSourceFor:Prefix(Pawn getter, Pawn eater, Boolean& __result, Thing& foodSource, ThingDef& foodDef, Boolean& desperate)
     - POSTFIX Orion.Hospitality: Void Hospitality.Patches.FoodUtility_Patch+TryFindBestFoodSourceFor_Patch:Postfix(Pawn getter, Pawn eater, Boolean& __result, Thing& foodSource, ThingDef& foodDef, Boolean& desperate)
 at RimWorld.JobGiver_GetFood.TryGiveJob (Verse.Pawn pawn) [0x000f9] in <69945a8ed6c540cf90b578de735e0605>:0 
     - PREFIX OskarPotocki.VFECore: Boolean AnimalBehaviours.VanillaExpandedFramework_JobGiver_GetFood_GetPriority_Patch:StopEatingThings(Pawn pawn)
     - POSTFIX Orion.Gastronomy: Void Gastronomy.Dining._JobGiver_GetFood_Patch+TryGiveJob:Postfix(Job& __result, Pawn pawn)
 at Verse.AI.ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00000] in <69945a8ed6c540cf90b578de735e0605>:0 
 at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x000fb] in <69945a8ed6c540cf90b578de735e0605>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/1776b61f-ceb9-48a2-9806-2043d909af06)

Grateful thanks!

**Comment by AnywayJustaBug** [comment]
I have the same bug. 

If it helps: when I played my round a few months ago, everything went smoothly. 

Hope it can be solved. I've been playing this medieval colony for a really long time.

**Comment by ZXUW** [comment]
Feb.23 update of Medieval Overhaul cause it.

**Comment by ZXUW** [comment]
It’s already been fixed by ViralReaction.

**Comment by AnywayJustaBug** [comment]
I reinstalled the game to be on the safe side and still have the error.

**Comment by ZXUW** [comment]
fixed now
